### ISSUE TITLE
L'affichage sous forme de tableau est il nécessaire/demandé ?

### ISSUE THREAD

**Issue by glenux** [dassimanuel000/Tp-estiam#3]
https://github.com/dassimanuel000/Tp-estiam/blob/8031de6591b4c9b38d63f796e0171489f3a8fa02/index.py#L55

En revanche, le fait de faire un `return` avec la liste des résultats était demandé :)

**Comment by dassimanuel000** [comment]
c'était pour mieux lire
le return ;)
